#!/bin/zsh

# Define Variables
FILEPATH="//d/workspace/tfod-wkspc"
IMAGE="edurs0/tfod-wkspc"
GPU_IMAGE="edurs0/tfod-wkspc-gpu"

print_usage() {
    echo "Usage: docker-run -f <FILEPATH> -g"
    echo "    -f FILEPATH the path to the workspace"
    echo "    -g use this tag if you have a TF2.x compatible GPU"
}


while getopts abo: c
do
    case $c in
        f)      FILEPATH=$OPTARG ;;
        g)      IMAGE=GPU_IMAGE ;;
        \?)     print_usage
                exit 2;;
    esac
done

echo $IMAGE
echo $FILEPATH

# Start Docker
#docker run \
    #--rm \
    #--name tfod \
    #-it \
    #-p 8888:8888 \
    #-p 6006:6006 \
    #-v $FILEPATH:/tensorflow/workspace \
    #$IMAGE

